### ISSUE TITLE
Script not running 

### ISSUE THREAD

**Issue by Rahulshah192006** [its-ag/discord-rpc#1]
![image](https://user-images.githubusercontent.com/80642384/218798422-2f188adf-f711-4ea0-8ea0-dc72cf09e55c.png)
 Getting this error

**Comment by ghost-2e63** [comment]
**Make sure you have python3 and pip installed.**

For arch based distros,
```
sudo pacnam -Sy python-pip
```
For ubuntu based distros, 
```
sudo apt install python3-pip
```
Open terminal, and run the following commands.

```sh
git clone https://github.com/its-ag/discord-rpc.git
cd discord-rpc
pip install -r requirements.txt
./start
```

**Comment by Rahulshah192006** [comment]
working bro

**Comment by Rahulshah192006** [comment]
bro aaj kaam karna band kar diya
